ANOMALY_WINDOW_ATTRIBUTION_COLUMNS = [
    "tail_id",
    "flight_id",
    "win_id",
    "timestamp_utc",
    "phase_state_detected",
    "phase_id_detected",
    "phase_confidence_detected",
    "distance_to_centroid_detected",
    "drift_magnitude",
    "breadth",
    "global_score",
    "p_value",
    "severity",
    "dominant_subsystem_id",
    "dominant_score_component",
    "panel_context",
    "subsystems",
    "attribution_context",
    "artifact_versions",
    "date_utc",
]

ANOMALY_TELEMETRY_ATTRIBUTION_COLUMNS = [
    "tail_id",
    "flight_id",
    "win_id",
    "timestamp_utc",
    "parameter_name",
    "parameter_value",
    "parameter_datatype_label",
    "system_id",
    "subsystem_id",
    "module_id",
    "window_global_score",
    "severity",
    "date_utc",
]

ANOMALY_EVENT_ATTRIBUTION_COLUMNS = [
    "tail_id",
    "flight_id",
    "win_id",
    "timestamp_utc",
    "parameter_name",
    "event_type_detected",
    "anomaly_type_detected",
    "anomaly_score_detected",
    "system_id",
    "subsystem_id",
    "module_id",
    "window_global_score",
    "severity",
    "date_utc",
]

ANOMALY_WINDOW_ATTRIBUTION_SCHEMA = """
tail_id string,
flight_id string,
win_id int,
timestamp_utc timestamp,
phase_state_detected string,
phase_id_detected int,
phase_confidence_detected double,
distance_to_centroid_detected double,
drift_magnitude double,
breadth double,
global_score double,
p_value double,
severity string,
dominant_subsystem_id string,
dominant_score_component string,
panel_context string,
subsystems array<string>,
attribution_context string,
artifact_versions string,
date_utc date
"""

ANOMALY_TELEMETRY_ATTRIBUTION_SCHEMA = """
tail_id string,
flight_id string,
win_id int,
timestamp_utc timestamp,
parameter_name string,
parameter_value string,
parameter_datatype_label string,
system_id string,
subsystem_id string,
module_id string,
window_global_score double,
severity string,
date_utc date
"""

ANOMALY_EVENT_ATTRIBUTION_SCHEMA = """
tail_id string,
flight_id string,
win_id int,
timestamp_utc timestamp,
parameter_name string,
event_type_detected string,
anomaly_type_detected string,
anomaly_score_detected double,
system_id string,
subsystem_id string,
module_id string,
window_global_score double,
severity string,
date_utc date
"""
