EXPLORER_TELEMETRY_COLUMNS = [
    "tail_id",
    "flight_id",
    "timestamp_utc",
    "parameter_name",
    "parameter_value",
    "parameter_value_clean",
    "unit",
    "rate_hz",
    "date_utc",
    "system_id",
    "subsystem_id",
    "module_id",
    "plot_value_raw",
    "plot_value_zscore",
    "plot_value_robust",
    "plot_value_default",
]

EXPLORER_PARAMETER_CATALOG_COLUMNS = [
    "parameter_name",
    "system_id",
    "subsystem_id",
    "module_id",
    "unit",
    "rate_hz",
    "row_count",
    "timestamp_min",
    "timestamp_max",
    "plot_mean",
    "plot_std",
    "plot_median",
    "plot_mad",
    "plot_min",
    "plot_max",
]

EXPLORER_EVENT_MARKERS_COLUMNS = [
    "tail_id",
    "flight_id",
    "timestamp_utc",
    "parameter_name",
    "event_type_detected",
    "anomaly_type_detected",
    "anomaly_score_detected",
    "marker_source",
    "severity",
    "window_global_score",
    "system_id",
    "subsystem_id",
    "module_id",
    "date_utc",
]

EXPLORER_ANOMALY_MARKERS_COLUMNS = [
    "tail_id",
    "flight_id",
    "win_id",
    "timestamp_utc",
    "parameter_name",
    "severity",
    "window_global_score",
    "parameter_value",
    "parameter_datatype_label",
    "system_id",
    "subsystem_id",
    "module_id",
    "date_utc",
]

EXPLORER_ANOMALY_WINDOWS_COLUMNS = [
    "tail_id",
    "flight_id",
    "win_id",
    "timestamp_utc",
    "severity",
    "global_score",
    "p_value",
    "dominant_subsystem_id",
    "dominant_score_component",
    "date_utc",
]

EXPLORER_PHASE_INTERVALS_COLUMNS = [
    "tail_id",
    "flight_id",
    "timestamp_start",
    "timestamp_end",
    "phase_label",
    "phase_id_detected",
    "phase_state_detected",
    "source",
    "date_utc",
]
