PHASE_WINDOWS_COLUMNS = [
    "tail_id",
    "flight_id",
    "win_id",
    "t_start",
    "t_end",
    "duration_ms",
    "event_count",
    "phase_id_detected",
    "phase_state_detected",
    "phase_confidence_detected",
    "distance_to_centroid_detected",
    "drift_magnitude",
    "breadth",
    "backbone_reconstruction_error",
    "backbone_residual_by_parameter",
    "x_c",
    "s_w",
    "date_utc",
]

PHASE_BASELINES_COLUMNS = [
    "tail_id",
    "phase_id_detected",
    "phase_name_detected",
    "s_w_centroid",
    "reconstruction_median",
    "reconstruction_mad",
    "distance_median",
    "distance_mad",
    "stable_window_count",
    "version",
]

PHASE_WINDOWS_SCHEMA = """
tail_id string,
flight_id string,
win_id int,
t_start timestamp,
t_end timestamp,
duration_ms int,
event_count int,
phase_id_detected int,
phase_state_detected string,
phase_confidence_detected double,
distance_to_centroid_detected double,
drift_magnitude double,
breadth double,
backbone_reconstruction_error double,
backbone_residual_by_parameter map<string,double>,
x_c array<double>,
s_w array<double>,
date_utc date,
feature_names array<string>,
selected_sensors_c array<string>,
selected_event_types array<string>,
selected_categorical_state_pairs array<string>,
selected_window_cooccurrence_pairs array<string>,
backbone_all_sensors array<string>
"""

PHASE_BASELINES_SCHEMA = """
tail_id string,
phase_id_detected int,
phase_name_detected string,
s_w_centroid array<double>,
reconstruction_median double,
reconstruction_mad double,
distance_median double,
distance_mad double,
stable_window_count int,
feature_names array<string>,
selected_sensors_c array<string>,
selected_event_types array<string>,
selected_categorical_state_pairs array<string>,
selected_window_cooccurrence_pairs array<string>,
backbone_all_sensors array<string>,
backbone_weights_b array<array<double>>,
version int
"""
