RAW_TELEMETRY_COLUMNS = [
    "tail_id",
    "flight_id",
    "timestamp_utc",
    "parameter_name",
    "parameter_value",
    "unit",
    "rate_hz",
    "date_utc",
]

SIMULATION_RAW_INPUT_COLUMNS = [
    "tail_id",
    "flight_id",
    "step_index",
    "timestamp_utc",
    "date_utc",
    "system_id",
    "subsystem_id",
    "module_id",
    "parameter_name",
    "sensor",
    "unit",
    "rate_hz",
    "behavior_family_label",
    "parameter_datatype_label",
    "parameter_value_clean",
    "parameter_value",
    "phase_label",
    "target_source",
    "misbehavior_active",
    "misbehavior_applied",
    "misbehavior_family_label",
    "misbehavior_detail_label",
    "misbehavior_window_id",
    "coupling_id_label",
    "event_type_label",
    "event_misbehavior_label",
    "anomaly_type_label",
    "anomaly_score_label",
    "fault_active",
    "fault_applied",
    "fault_family_label",
    "fault_type",
    "fault_window_id",
]


def SIMULATION_RAW_INPUT_SCHEMA():
    from pyspark.sql import types as T

    return T.StructType(
        [
            T.StructField("tail_id", T.StringType(), False),
            T.StructField("flight_id", T.StringType(), False),
            T.StructField("step_index", T.IntegerType(), True),
            T.StructField("timestamp_utc", T.TimestampType(), False),
            T.StructField("date_utc", T.DateType(), False),
            T.StructField("system_id", T.StringType(), True),
            T.StructField("subsystem_id", T.StringType(), True),
            T.StructField("module_id", T.StringType(), True),
            T.StructField("parameter_name", T.StringType(), False),
            T.StructField("sensor", T.StringType(), True),
            T.StructField("unit", T.StringType(), True),
            T.StructField("rate_hz", T.DoubleType(), True),
            T.StructField("behavior_family_label", T.StringType(), True),
            T.StructField("parameter_datatype_label", T.StringType(), True),
            T.StructField("parameter_value_clean", T.StringType(), True),
            T.StructField("parameter_value", T.StringType(), True),
            T.StructField("phase_label", T.StringType(), True),
            T.StructField("target_source", T.StringType(), True),
            T.StructField("misbehavior_active", T.BooleanType(), True),
            T.StructField("misbehavior_applied", T.BooleanType(), True),
            T.StructField("misbehavior_family_label", T.StringType(), True),
            T.StructField("misbehavior_detail_label", T.StringType(), True),
            T.StructField("misbehavior_window_id", T.StringType(), True),
            T.StructField("coupling_id_label", T.StringType(), True),
            T.StructField("event_type_label", T.StringType(), True),
            T.StructField("event_misbehavior_label", T.StringType(), True),
            T.StructField("anomaly_type_label", T.StringType(), True),
            T.StructField("anomaly_score_label", T.DoubleType(), True),
            T.StructField("fault_active", T.BooleanType(), True),
            T.StructField("fault_applied", T.BooleanType(), True),
            T.StructField("fault_family_label", T.StringType(), True),
            T.StructField("fault_type", T.StringType(), True),
            T.StructField("fault_window_id", T.StringType(), True),
        ]
    )
