WINDOWS_COLUMNS = [
    "tail_id",
    "flight_id",
    "win_id",
    "t_start",
    "t_end",
    "duration_ms",
    "event_count",
    "sensor_count",
    "event_type_counts",
    "zoh_snapshot",
    "close_reason",
    "zoh_version",
    "date_utc",
]

WINDOW_POLICY_PROFILE_COLUMNS = [
    "profile_id",
    "profile_scope",
    "candidate_rank",
    "is_selected",
    "max_ms",
    "event_threshold",
    "min_ms",
    "inactivity_timeout_ms",
    "objective_score",
    "balance_penalty",
    "predicted_window_count",
    "mean_duration_ms",
    "p95_duration_ms",
    "mean_event_count",
    "p95_event_count",
    "mean_sensor_count",
    "p95_sensor_count",
    "mean_event_type_count",
    "p95_event_type_count",
    "event_threshold_close_rate",
    "max_ms_close_rate",
    "event_threshold_plus_max_ms_close_rate",
    "end_of_stream_close_rate",
    "pair_cost_proxy",
    "same_window_pair_expansion_proxy",
    "sampled_event_count",
    "sampled_flight_count",
]

WINDOWS_SCHEMA = """
tail_id string,
flight_id string,
win_id int,
t_start timestamp,
t_end timestamp,
duration_ms int,
event_count int,
sensor_count int,
event_type_counts map<string,int>,
zoh_snapshot map<string,string>,
close_reason string,
zoh_version int,
date_utc date
"""

WINDOW_X_SCHEMA = """
tail_id string,
flight_id string,
win_id int,
t_start timestamp,
t_end timestamp,
duration_ms int,
event_count int,
date_utc date,
event_type_counts map<string,int>,
continuous_event_summary struct<
  slope_run_count_by_parameter:map<string,int>,
  slope_reinforcement_count_by_parameter:map<string,int>,
  slope_signed_impulse_by_parameter:map<string,double>,
  slope_abs_impulse_by_parameter:map<string,double>,
  slope_peak_abs_delta_by_parameter:map<string,double>,
  switch_count_by_parameter:map<string,int>,
  threshold_count_by_parameter:map<string,int>,
  oscillation_count_by_parameter:map<string,int>,
  drift_guard_count_by_parameter:map<string,int>
>,
continuous_vector_t_end map<string,double>,
continuous_vector_t_end_scaled map<string,double>,
categorical_state_t_end map<string,string>,
drift_magnitude_profiled double,
phase_label string
"""


def WINDOW_POLICY_PROFILE_SCHEMA():
    from pyspark.sql import types as T

    return T.StructType(
        [
            T.StructField("profile_id", T.StringType(), False),
            T.StructField("profile_scope", T.StringType(), False),
            T.StructField("candidate_rank", T.IntegerType(), False),
            T.StructField("is_selected", T.BooleanType(), False),
            T.StructField("max_ms", T.IntegerType(), False),
            T.StructField("event_threshold", T.IntegerType(), False),
            T.StructField("min_ms", T.IntegerType(), False),
            T.StructField("inactivity_timeout_ms", T.IntegerType(), False),
            T.StructField("objective_score", T.DoubleType(), False),
            T.StructField("balance_penalty", T.DoubleType(), False),
            T.StructField("predicted_window_count", T.LongType(), False),
            T.StructField("mean_duration_ms", T.DoubleType(), False),
            T.StructField("p95_duration_ms", T.DoubleType(), False),
            T.StructField("mean_event_count", T.DoubleType(), False),
            T.StructField("p95_event_count", T.DoubleType(), False),
            T.StructField("mean_sensor_count", T.DoubleType(), False),
            T.StructField("p95_sensor_count", T.DoubleType(), False),
            T.StructField("mean_event_type_count", T.DoubleType(), False),
            T.StructField("p95_event_type_count", T.DoubleType(), False),
            T.StructField("event_threshold_close_rate", T.DoubleType(), False),
            T.StructField("max_ms_close_rate", T.DoubleType(), False),
            T.StructField("event_threshold_plus_max_ms_close_rate", T.DoubleType(), False),
            T.StructField("end_of_stream_close_rate", T.DoubleType(), False),
            T.StructField("pair_cost_proxy", T.DoubleType(), False),
            T.StructField("same_window_pair_expansion_proxy", T.DoubleType(), False),
            T.StructField("sampled_event_count", T.LongType(), False),
            T.StructField("sampled_flight_count", T.IntegerType(), False),
        ]
    )
