"""Objective modeling and evaluation for run-level tuning workflows."""

from libs.tuning.benchmark_invocation import build_benchmark_dir, validate_benchmark_args
from libs.tuning.benchmark_execution import (
    build_replay_run_command,
    build_run_command,
    clone_replay_source_run,
)
from libs.tuning.benchmark_runner import run_benchmark_variant
from libs.tuning.benchmark_search import (
    KNOWN_SEARCH_STAGES,
    KNOWN_SEARCH_STRATEGIES,
    SEARCH_SPEC_BY_STAGE,
    BenchmarkSearchDimension,
    BenchmarkSearchSpec,
    build_search_variants,
    resolve_search_spec,
)
from libs.tuning.benchmark_runtime import (
    all_validation_metrics_from_harness,
    build_benchmark_result,
    find_child_run_dir,
    load_json,
    replay_drift_status,
    selected_validation_metrics_for_objective,
    stage_elapsed_ms,
    validation_metric_index,
)
from libs.tuning.benchmark_variants import (
    FULL_SWEEP_ARG_VALUE_BY_NAME,
    SAFE_SMALL_SEGMENT_ENV,
    VARIANT_BY_NAME,
    VARIANT_SET_BY_NAME,
    BenchmarkVariant,
)
from libs.tuning.benchmark_planning import (
    EVALUATION_END_STAGE_BY_TIER,
    build_variant_plan_payload,
    build_variant_replay_plan_payload,
    infer_replay_target_stage,
    merged_objective_overrides,
    resolved_objective_payload,
    resolve_effective_evaluation_tier,
    resolve_effective_objective_name,
    resolve_effective_objective_spec,
    resolve_evaluation_end_stage,
    resolve_replay_end_stage,
)
from libs.tuning.benchmark_reporting import (
    BenchmarkResult,
    build_experiment_plan_markdown,
    build_experiment_plan_payload,
    build_markdown_summary,
    build_summary_payload,
    count_by_result_field,
    count_metric_names,
    replay_drift_status_counts,
    results_by_variant,
    variant_aggregate_payload,
)
from libs.tuning.objectives import (
    DEFAULT_COMPARE_BY,
    DEFAULT_OBJECTIVE_NAME_BY_MODE,
    KNOWN_OBJECTIVE_SPEC_NAMES,
    ObjectiveConstraint,
    ObjectiveEvaluation,
    ObjectiveMetricRef,
    ObjectiveSpec,
    ObjectiveTerm,
    build_default_objective_spec,
    evaluate_objective_spec,
    load_objective_spec,
    objective_spec_from_payload,
    resolve_default_objective_name,
    resolve_objective_evaluation_tier,
    resolve_objective_required_end_stage,
    resolve_objective_spec,
)
from libs.tuning.presets import KNOWN_OBJECTIVE_PRESET_NAMES, OBJECTIVE_PRESET_BY_NAME, ObjectivePreset
from libs.tuning.reporting import write_objective_evaluation_report
from libs.tuning.validation_panels import (
    DEFAULT_VALIDATION_PANEL_LIMIT,
    DEFAULT_VALIDATION_PANEL_MODE,
    KNOWN_VALIDATION_PANEL_MODES,
    VALIDATION_PANEL_SHORTLIST,
    build_validation_metric_panel,
)

__all__ = [
    "DEFAULT_COMPARE_BY",
    "DEFAULT_OBJECTIVE_NAME_BY_MODE",
    "EVALUATION_END_STAGE_BY_TIER",
    "FULL_SWEEP_ARG_VALUE_BY_NAME",
    "SAFE_SMALL_SEGMENT_ENV",
    "KNOWN_OBJECTIVE_SPEC_NAMES",
    "KNOWN_OBJECTIVE_PRESET_NAMES",
    "KNOWN_SEARCH_STAGES",
    "KNOWN_SEARCH_STRATEGIES",
    "OBJECTIVE_PRESET_BY_NAME",
    "SEARCH_SPEC_BY_STAGE",
    "VARIANT_BY_NAME",
    "VARIANT_SET_BY_NAME",
    "KNOWN_VALIDATION_PANEL_MODES",
    "DEFAULT_VALIDATION_PANEL_MODE",
    "DEFAULT_VALIDATION_PANEL_LIMIT",
    "VALIDATION_PANEL_SHORTLIST",
    "BenchmarkVariant",
    "BenchmarkSearchDimension",
    "BenchmarkSearchSpec",
    "BenchmarkResult",
    "ObjectiveConstraint",
    "ObjectiveEvaluation",
    "ObjectiveMetricRef",
    "ObjectivePreset",
    "ObjectiveSpec",
    "ObjectiveTerm",
    "all_validation_metrics_from_harness",
    "build_benchmark_dir",
    "build_default_objective_spec",
    "build_benchmark_result",
    "build_search_variants",
    "build_replay_run_command",
    "build_run_command",
    "run_benchmark_variant",
    "build_experiment_plan_markdown",
    "build_experiment_plan_payload",
    "build_markdown_summary",
    "build_summary_payload",
    "build_variant_plan_payload",
    "build_variant_replay_plan_payload",
    "build_validation_metric_panel",
    "clone_replay_source_run",
    "count_by_result_field",
    "evaluate_objective_spec",
    "find_child_run_dir",
    "infer_replay_target_stage",
    "load_json",
    "load_objective_spec",
    "merged_objective_overrides",
    "resolved_objective_payload",
    "objective_spec_from_payload",
    "count_metric_names",
    "replay_drift_status_counts",
    "replay_drift_status",
    "resolve_effective_evaluation_tier",
    "resolve_effective_objective_name",
    "resolve_effective_objective_spec",
    "resolve_default_objective_name",
    "resolve_evaluation_end_stage",
    "resolve_objective_required_end_stage",
    "resolve_objective_spec",
    "resolve_replay_end_stage",
    "resolve_search_spec",
    "resolve_objective_evaluation_tier",
    "results_by_variant",
    "selected_validation_metrics_for_objective",
    "stage_elapsed_ms",
    "validate_benchmark_args",
    "validation_metric_index",
    "variant_aggregate_payload",
    "write_objective_evaluation_report",
]
