from __future__ import annotations

from html import escape
from pathlib import Path
import textwrap


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs/current/s3ntinel_current_architecture.svg"
W, H = 3840, 2160

BG = "#F3F6F8"
WHITE = "#FFFFFF"
NAVY = "#10243A"
DARK = "#071626"
SLATE = "#526678"
MUTED = "#708296"
LINE = "#C9D4DE"
BLUE = "#176B87"
BLUE_PALE = "#E8F3F7"
PURPLE = "#7052A3"
PURPLE_PALE = "#F0ECF8"
GREEN = "#258361"
GREEN_PALE = "#E8F5EF"
ORANGE = "#D26C10"
ORANGE_PALE = "#FFF1E2"
RED = "#B94444"
RED_PALE = "#FBEAEA"


class Svg:
    def __init__(self) -> None:
        self.parts = [
            f'<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{H}" viewBox="0 0 {W} {H}" role="img" aria-labelledby="title desc">',
            "<title id=\"title\">S3NTINEL current V2 architecture single-pane reference</title>",
            "<desc id=\"desc\">Current Spark-oriented fitting and inference stages, active artifacts, mathematical representations, validation, replay, and implementation boundaries.</desc>",
            "<!-- Generated by tools/render_current_architecture_svg.py from current repository contracts. -->",
            "<defs>",
            '<filter id="shadow" x="-10%" y="-10%" width="120%" height="130%">',
            '<feDropShadow dx="0" dy="3" stdDeviation="5" flood-color="#10243A" flood-opacity="0.10"/>',
            "</filter>",
            '<marker id="arrow" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto">',
            '<path d="M0,0 L0,6 L9,3 z" fill="#526678"/>',
            "</marker>",
            "</defs>",
            f'<rect width="{W}" height="{H}" fill="{BG}"/>',
        ]

    def rect(self, x, y, w, h, fill=WHITE, stroke=LINE, sw=2, rx=18, shadow=False) -> None:
        filt = ' filter="url(#shadow)"' if shadow else ""
        self.parts.append(
            f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="{rx}" fill="{fill}" '
            f'stroke="{stroke}" stroke-width="{sw}"{filt}/>'
        )

    def line(self, x1, y1, x2, y2, color=LINE, sw=2, arrow=False, dash=None) -> None:
        marker = ' marker-end="url(#arrow)"' if arrow else ""
        dashed = f' stroke-dasharray="{dash}"' if dash else ""
        self.parts.append(
            f'<line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}" stroke="{color}" '
            f'stroke-width="{sw}"{dashed}{marker}/>'
        )

    def text(self, x, y, value, size=16, color=NAVY, weight=400, anchor="start", family="DejaVu Sans") -> None:
        self.parts.append(
            f'<text x="{x}" y="{y}" font-family="{family}, sans-serif" font-size="{size}" '
            f'font-weight="{weight}" fill="{color}" text-anchor="{anchor}">{escape(str(value))}</text>'
        )

    def wrapped(self, x, y, value, width, size=16, color=NAVY, weight=400, leading=None, bullet=False) -> float:
        leading = leading or int(size * 1.34)
        chars = max(int(width / (size * 0.55)), 12)
        prefix = "• " if bullet else ""
        indent = "  " if bullet else ""
        lines = textwrap.wrap(
            prefix + value,
            width=chars,
            subsequent_indent=indent,
            break_long_words=False,
            break_on_hyphens=False,
        ) or [""]
        for index, line in enumerate(lines):
            self.text(x, y + index * leading, line, size, color, weight)
        return y + len(lines) * leading

    def panel(self, x, y, w, h, title, color, pale) -> float:
        self.rect(x, y, w, h, WHITE, color, 2, 18, True)
        self.rect(x, y, w, 48, pale, color, 0, 18)
        self.parts.append(f'<rect x="{x}" y="{y + 29}" width="{w}" height="19" fill="{pale}"/>')
        self.text(x + 18, y + 33, title, 20, color, 800)
        return y + 72

    def pill(self, x, y, w, label, color, size=13) -> None:
        self.rect(x, y, w, 31, color, color, 0, 15)
        self.text(x + w / 2, y + 22, label, size, WHITE, 800, "middle")

    def equation(self, x, y, w, value, color=PURPLE, fill=PURPLE_PALE, size=15) -> float:
        self.rect(x, y, w, 36, fill, color, 1, 8)
        self.text(x + 10, y + 25, value, size, color, 650, family="DejaVu Sans Mono")
        return y + 44

    def bullets(self, x, y, items, width, size=15, color=NAVY, gap=7) -> float:
        cursor = y
        for item in items:
            cursor = self.wrapped(x, cursor, item, width, size, color, 400, bullet=True) + gap
        return cursor

    def stage(self, x, y, w, h, number, name, artifact, color) -> None:
        self.rect(x, y, w, h, WHITE, color, 1, 12)
        self.rect(x, y, 57, h, color, color, 0, 12)
        self.parts.append(f'<rect x="{x + 43}" y="{y}" width="14" height="{h}" fill="{color}"/>')
        self.text(x + 28, y + 31, number, 17, WHITE, 800, "middle")
        self.text(x + 70, y + 27, name, 15, color, 800)
        self.text(x + 70, y + 50, artifact, 12, SLATE, 500)

    def finish(self) -> None:
        self.parts.append("</svg>")
        OUT.write_text("\n".join(self.parts), encoding="utf-8")


def add_header(s: Svg) -> None:
    s.text(42, 55, "S3NTINEL", 45, NAVY, 800)
    s.text(310, 55, "CURRENT V2 ARCHITECTURE • SINGLE-PANE REPOSITORY REFERENCE", 30, BLUE, 700)
    s.text(
        42, 91,
        "Structural Streaming Sparse Event Nexus for Telemetry Inference with Network Envelope Learning",
        18, SLATE, 500,
    )
    s.rect(2865, 24, 933, 72, DARK, DARK, 0, 16)
    s.text(2890, 51, "ACTIVE SYSTEM BOUNDARY", 14, "#85D7E8", 800)
    s.text(2890, 78, "Spark evidence pipeline • persisted artifacts • simulation-backed validation", 17, WHITE, 600)
    s.line(42, 112, 3798, 112, NAVY, 2)


def add_pipeline(s: Svg) -> None:
    x, y, w, h = 42, 128, 3756, 376
    s.rect(x, y, w, h, WHITE, BLUE, 2, 18, True)
    s.text(x + 18, y + 32, "ACTIVE PERSISTED STAGE FLOW", 20, BLUE, 800)
    s.text(x + w - 18, y + 32, "Grouped runners: 97 fitting • 98 inference • 99 full • 96 fixed-reference inference", 15, SLATE, 600, "end")

    s.pill(x + 18, y + 61, 122, "FITTING", PURPLE)
    fitting = [
        ("00", "INGEST", "raw_telemetry"),
        ("10", "PROFILE", "datatype • scale"),
        ("12", "BEHAVIOR", "primitive • family"),
        ("15", "EVENT FIT", "event profile"),
        ("20", "EVENTS", "detected events"),
        ("25", "POLICY", "window policy"),
        ("30", "WINDOWS", "adaptive windows"),
        ("40", "BACKBONE", "features • ridge"),
        ("50", "GRAPHS", "components • fusion"),
        ("60", "HIERARCHY", "map • edge evidence"),
    ]
    sx, sy, bw, bh, gap = x + 18, y + 104, 351, 67, 22
    for index, (number, name, artifact) in enumerate(fitting):
        s.stage(sx, sy, bw, bh, number, name, artifact, PURPLE if index < 7 else BLUE)
        if index < len(fitting) - 1:
            s.line(sx + bw + 3, sy + bh / 2, sx + bw + gap - 4, sy + bh / 2, SLATE, 2, True)
        sx += bw + gap

    s.pill(x + 18, y + 206, 136, "INFERENCE", GREEN)
    inference = [
        ("70", "PHASE FIT / APPLY", "windows • baselines • reference model"),
        ("80", "RAW SCORES", "8 score channels • candidate evidence"),
        ("85", "CALIBRATE", "phase-conditioned rarity • emit_ready"),
        ("90", "ATTRIBUTE", "window • telemetry • event • candidates"),
        ("95", "EXPLORER", "thin operator / notebook bundle"),
    ]
    sx, sy, bw, bh, gap = x + 205, y + 247, 676, 78, 30
    for index, (number, name, artifact) in enumerate(inference):
        s.stage(sx, sy, bw, bh, number, name, artifact, GREEN if index < 3 else ORANGE)
        if index < len(inference) - 1:
            s.line(sx + bw + 3, sy + bh / 2, sx + bw + gap - 4, sy + bh / 2, SLATE, 2, True)
        sx += bw + gap

    s.rect(x + 18, y + 337, 1710, 26, PURPLE_PALE, PURPLE, 0, 8)
    s.text(x + 30, y + 356, "35 WINDOW FEATURES APPLY • reference inference only • fixed scaling profile • no structural refit", 13, PURPLE, 700)
    s.rect(x + 1747, y + 337, 1991, 26, ORANGE_PALE, ORANGE, 0, 8)
    s.text(x + 1759, y + 356, "72 PHASE LABEL CENTROIDS • simulation validation only • truth labels • excluded from production grouped runners", 13, ORANGE, 700)


def col1(s: Svg, x: int, w: int) -> None:
    y = 524
    cy = s.panel(x, y, w, 250, "1  CURRENT SYSTEM BOUNDARY", BLUE, BLUE_PALE)
    s.wrapped(x + 18, cy, "Spark-oriented telemetry anomaly detection and attribution with a simulation validation harness.", w - 36, 16, NAVY, 600)
    s.bullets(x + 18, cy + 54, [
        "Motivated by A-MATS-captured ARINC 664 Part 7 / AFDX avionics telemetry and CBM+ investigation.",
        "Consumes normalized observed telemetry and emits calibrated anomaly evidence plus attribution artifacts.",
        "Does not currently claim live A-MATS, AFDX, or BLADE integration.",
    ], w - 36, 14)

    y = 792
    cy = s.panel(x, y, w, 360, "2  SIGNAL → EVENT → WINDOW SEMANTICS", GREEN, GREEN_PALE)
    s.text(x + 18, cy, "Observed signal contract", 16, GREEN, 800)
    s.wrapped(x + 18, cy + 24, "parameter_value drives fitting and inference; parameter_value_clean is simulation truth/debug context only.", w - 36, 13, NAVY)
    s.text(x + 18, cy + 78, "Reusable parameter metadata", 16, GREEN, 800)
    s.bullets(x + 18, cy + 103, [
        "parameter_datatype_profile + continuous_scaling_profile",
        "parameter_behavior_primitive_profile → parameter_behavior_profile",
        "parameter_event_profile → detected events",
    ], w - 36, 14, gap=5)
    s.text(x + 18, cy + 203, "Adaptive segmentation", 16, GREEN, 800)
    s.wrapped(x + 18, cy + 228, "window_policy_profile selects max duration and event threshold; stage 30 materializes windows.", w - 36, 13, NAVY)
    s.wrapped(x + 18, cy + 267, "window_features = ZOH continuous state at t_end + scaled vectors + categorical state + event counts/summaries + drift.", w - 36, 13, BLUE, 600)

    y = 1170
    cy = s.panel(x, y, w, 330, "3  FIT ONCE • REUSE • APPLY", PURPLE, PURPLE_PALE)
    s.text(x + 18, cy, "Normal inference reuses fitted semantics", 16, PURPLE, 800)
    s.bullets(x + 18, cy + 28, [
        "datatype, scaling, behavior, event, window-policy, backbone, graph, hierarchy, and phase artifacts",
        "phase_reference_model persists feature config, robust statistics, ordered centroids, scales, and transition-support bands",
        "target observations rematerialize events, windows, and features before fixed-model phase application",
    ], w - 36, 14)
    s.rect(x + 18, cy + 200, w - 36, 70, RED_PALE, RED, 1, 10)
    s.wrapped(x + 32, cy + 229, "Reference inference does not rerun stages 10, 12, 15, 25, 40, 50, or 60 and does not fit phase structure from the target flight.", w - 64, 14, RED, 650)

    y = 1518
    cy = s.panel(x, y, w, 275, "4  EXECUTION ENTRYPOINTS", ORANGE, ORANGE_PALE)
    rows = [
        ("97", "fit reusable artifacts", PURPLE),
        ("98", "apply inference stages", GREEN),
        ("96", "fixed-reference target inference", BLUE),
        ("99", "full fit + inference under one parent MLflow run", ORANGE),
    ]
    for index, (number, desc, color) in enumerate(rows):
        yy = cy + index * 43 - 19
        s.pill(x + 18, yy, 62, number, color, 14)
        s.text(x + 94, yy + 22, desc, 14, NAVY, 600)
    s.wrapped(x + 18, cy + 176, "Grouped runners support stage slicing and replay from manifests whose replayable_from inputs are valid.", w - 36, 14, SLATE)

    y = 1811
    cy = s.panel(x, y, w, 243, "5  CANONICAL WINDOW IDENTITY", BLUE, BLUE_PALE)
    s.equation(x + 18, cy, w - 36, "window identity = (tail_id, flight_id, win_id)", BLUE, BLUE_PALE, 15)
    s.bullets(x + 18, cy + 55, [
        "Canonical labels use *_label; detector fields use *_detected.",
        "Co-occurrence and precedence are graph relations, not detector event types.",
        "Persisted artifact and field names come from schemas and the glossary.",
    ], w - 36, 14, gap=5)


def col2(s: Svg, x: int, w: int) -> None:
    y = 524
    cy = s.panel(x, y, w, 370, "6  ROBUST COORDINATES & BACKBONE", PURPLE, PURPLE_PALE)
    s.wrapped(x + 18, cy, "The reconstruction backbone summarizes normal continuous structure over robust-scaled end-of-window vectors.", w - 36, 15)
    cursor = s.equation(x + 18, cy + 48, w - 36, "x_scaled[j] = (x[j] − median[j]) / max(IQR[j], ε)")
    cursor = s.equation(x + 18, cursor, w - 36, "E(j) = Σw xw[j]²")
    cursor = s.equation(x + 18, cursor, w - 36, "G = Σw xCᵀxC     •     H = Σw xCᵀx")
    cursor = s.equation(x + 18, cursor, w - 36, "B = (G + λI)⁻¹H")
    s.wrapped(x + 18, cursor + 2, "Event summaries influence sensor ranking only; they do not enter G/H or the ridge solve.", w - 36, 14, RED, 650)

    y = 912
    cy = s.panel(x, y, w, 505, "7  DISTINCT GRAPH LENSES", BLUE, BLUE_PALE)
    graph_blocks = [
        ("PRECISION • undirected", "Θ=(Σ+λI)⁻¹ • ρij=−Θij/√(ΘiiΘjj) • weight=|ρij|", "conditional continuous association", PURPLE),
        ("EVENT • undirected", "PMI=log(pij/(pi·pj)) • NPMI=PMI/(−log pij) • weight=max(0,NPMI)", "same-window association beyond marginals", BLUE),
        ("LAG PROFILE / GRAPH • directed", "nearest-prior, per-band conditional tendency → collapsed compatibility weight", "delayed temporal relation with support and lag bands", ORANGE),
        ("TRANSITION • directed", "adjacent-event row-normalized transition probability", "immediate sequence tendency", GREEN),
        ("FUSED • structural evidence", "weighted compatible components; directed evidence retained separately", "combined evidence for bounded hierarchy fitting", RED),
    ]
    cursor = cy
    for title, equation, interpretation, color in graph_blocks:
        s.text(x + 18, cursor, title, 15, color, 800)
        s.rect(x + 18, cursor + 8, w - 36, 31, PURPLE_PALE if color == PURPLE else BLUE_PALE, color, 1, 7)
        s.text(x + 28, cursor + 30, equation, 12, color, 650, family="DejaVu Sans Mono")
        s.text(x + 28, cursor + 55, interpretation, 13, SLATE, 500)
        cursor += 78

    y = 1435
    cy = s.panel(x, y, w, 310, "8  HIERARCHY & RETAINED EVIDENCE", GREEN, GREEN_PALE)
    s.bullets(x + 18, cy, [
        "Stage 60 consumes persisted fused_graph + graph_parameter_universe from the same fitting run.",
        "Spark ranks neighbors and retains mutual top-k edges; only the pruned result reaches bounded clustering/rollup.",
        "hierarchy_sensor_map assigns parameter → module → subsystem → system IDs.",
        "hierarchy_edge_evidence preserves endpoint ranks, fused components, hierarchy IDs, and directed lag evidence both ways.",
    ], w - 36, 14)
    s.wrapped(x + 18, cy + 188, "Temporal direction supplies evidence; it does not become a containment or causal direction.", w - 36, 14, RED, 650)

    y = 1763
    cy = s.panel(x, y, w, 311, "9  PHASE MODEL • CURRENT AVIONICS CONTRACT", ORANGE, ORANGE_PALE)
    s.bullets(x + 18, cy, [
        "Selected structure vectors → Spark-first per-flight clustering → progress-mass seeding → ordered support bands.",
        "Monotone transition-aware decode + minimum dwell emits phase_windows and phase_baselines.",
        "Primary phases: gate_turnaround, takeoff_climb, cruise, descent_approach.",
        "Auxiliary stable / transition_region metadata does not add a fifth learned phase.",
    ], w - 36, 14)
    s.rect(x + 18, cy + 192, w - 36, 55, RED_PALE, RED, 1, 9)
    s.wrapped(x + 30, cy + 216, "A fleet-learned revisitable transition model is outside the current contract.", w - 60, 14, RED, 700)


def col3(s: Svg, x: int, w: int) -> None:
    y = 524
    cy = s.panel(x, y, w, 420, "10  RAW SCORING & CALIBRATION", PURPLE, PURPLE_PALE)
    s.wrapped(x + 18, cy, "WindowScoresRawTable combines fitted phase and structural context; WindowScoresCalibratedTable converts scores into phase-conditioned rarity.", w - 36, 15)
    channels = [
        "regime_deviation", "reconstruction_error", "event_discordance", "bound_violation",
        "accumulation_violation", "response_violation", "state_violation", "coherence_break",
    ]
    left, right = channels[:4], channels[4:]
    for index, label in enumerate(left):
        s.pill(x + 18, cy + 70 + index * 42, 398, label.upper(), PURPLE, 11)
    for index, label in enumerate(right):
        s.pill(x + 438, cy + 70 + index * 42, w - 456, label.upper(), BLUE, 11)
    s.rect(x + 18, cy + 239, w - 36, 64, GREEN_PALE, GREEN, 1, 10)
    s.wrapped(x + 32, cy + 264, "emit_ready requires a warm-enough phase bucket and medium/high raw severity—or a phase-rare low-severity window.", w - 64, 13, GREEN, 650)
    s.wrapped(x + 18, cy + 326, "parameter_score_evidence is bounded diagnostic payload; it does not change severity or emission semantics.", w - 36, 13, RED, 600)

    y = 962
    cy = s.panel(x, y, w, 350, "11  ATTRIBUTION IS DOWNSTREAM EXPLANATION", ORANGE, ORANGE_PALE)
    s.wrapped(x + 18, cy, "Stage 90 filters calibrated windows and materializes inspectable evidence without reimplementing scoring.", w - 36, 15)
    outputs = [
        ("WINDOW", "dominant system / subsystem / module + panel context"),
        ("TELEMETRY", "window-local parameter and sample evidence"),
        ("EVENT", "window-local event evidence"),
        ("CANDIDATES", "one row per emitted window/parameter candidate; rank + cuts + hierarchy"),
    ]
    for index, (label, desc) in enumerate(outputs):
        yy = cy + 69 + index * 48
        s.pill(x + 18, yy - 22, 150, label, ORANGE if index < 3 else PURPLE, 12)
        s.wrapped(x + 184, yy, desc, w - 202, 13, NAVY)
    s.wrapped(x + 18, cy + 252, "Attribution cannot recover targets absent from upstream score evidence or the retained hierarchy.", w - 36, 13, RED, 650)

    y = 1330
    cy = s.panel(x, y, w, 380, "12  PERSISTED OUTPUT FAMILIES", BLUE, BLUE_PALE)
    groups = [
        ("SEMANTICS", "datatype • scaling • behavior primitive • behavior family • event profile", GREEN),
        ("WINDOWS", "window policy • windows • window_features", BLUE),
        ("STRUCTURE", "backbone • sensor energy • component graphs • fused graph • hierarchy", PURPLE),
        ("PHASE / SCORE", "phase windows • baselines • reference model • raw/calibrated scores", ORANGE),
        ("ATTRIBUTION", "window • telemetry • event • parameter candidate evidence", RED),
        ("REPORTS", "stage manifests • pipeline summary • harness • objective • benchmark ledgers", GREEN),
    ]
    cursor = cy - 18
    for label, desc, color in groups:
        cursor += 48
        s.pill(x + 18, cursor - 23, 150, label, color, 11)
        s.wrapped(x + 184, cursor, desc, w - 202, 13, NAVY)

    y = 1728
    cy = s.panel(x, y, w, 346, "13  VALIDATION HARNESS & CLAIM BOUNDARIES", GREEN, GREEN_PALE)
    s.bullets(x + 18, cy, [
        "validation_harness_report joins fit parameters, model metrics, compute metrics, simulator context, and lineage.",
        "objective_evaluation_report ranks comparable runs by mode-aware quality with separate compute tie-breaks.",
        "benchmark tiers separate detection, parameter, subsystem, and module eligibility and failure diagnosis.",
        "Phase evaluation separates steady-phase macro F1, exact transition-window overlap, and boundary-event alignment.",
    ], w - 36, 14)
    s.rect(x + 18, cy + 224, w - 36, 58, RED_PALE, RED, 1, 9)
    s.wrapped(x + 30, cy + 249, "Simulation evidence is scoped to authored truth and declared recoverability; it is not operational aircraft-performance evidence.", w - 60, 13, RED, 700)


def col4(s: Svg, x: int, w: int) -> None:
    y = 524
    cy = s.panel(x, y, w, 350, "14  REPLAY, MANIFESTS & LINEAGE", BLUE, BLUE_PALE)
    s.bullets(x + 18, cy, [
        "Every stage persists output tables, summary JSON, manifest, input/output inventory, row counts, and wall time.",
        "Grouped runs produce pipeline/full-run summaries, validation and objective reports, per-stage manifests, and MLflow lineage.",
        "Replay resumes only when the first resumed stage has valid replayable_from inputs.",
        "Graph and hierarchy artifacts must remain from one fitting run; stage 60 consumes persisted graph evidence rather than recomputing it.",
    ], w - 36, 14)
    s.rect(x + 18, cy + 224, w - 36, 61, GREEN_PALE, GREEN, 1, 9)
    s.wrapped(x + 30, cy + 250, "Fixed artifacts + immutable manifests make model comparisons inspectable and reversible.", w - 60, 14, GREEN, 700)

    y = 892
    cy = s.panel(x, y, w, 410, "15  SPARK HOT PATH & BOUNDED BRIDGES", PURPLE, PURPLE_PALE)
    s.bullets(x + 18, cy, [
        "Stage 20 uses segmented Spark sequence kernels over (tail_id, flight_id, parameter_name).",
        "Stage 40 keeps facts distributed; only sensor-energy and per-flight G/H aggregates reach the final bounded solve.",
        "Stage 50 builds precision, event, lag, transition, and fusion in Spark; only pruned hierarchy edges cross to bounded clustering.",
        "Stage 70 uses segmented Spark assignment; only bounded global configuration remains driver-side.",
        "Stage 80 keeps the main score fact table distributed and collects bounded reference artifacts.",
    ], w - 36, 14)
    s.rect(x + 18, cy + 283, w - 36, 63, RED_PALE, RED, 1, 9)
    s.wrapped(x + 30, cy + 308, "No toPandas() on growing fact tables; collect() only explicitly bounded reference artifacts; fail fast above configured limits.", w - 60, 13, RED, 700)

    y = 1320
    cy = s.panel(x, y, w, 330, "16  PACKAGE OWNERSHIP", ORANGE, ORANGE_PALE)
    ownership = [
        ("pipelines/", "ordering • config • persistence • manifests • MLflow"),
        ("libs/io", "Table / Frame / schema and merge contracts"),
        ("libs/profiling + events + windows", "signal semantics and segmentation"),
        ("libs/backbone + graph + phase", "structural and operating-regime models"),
        ("libs/scoring + anomaly", "rarity, emission, and explanation"),
        ("libs/simulation + tuning", "truth harness, reports, comparisons, search"),
    ]
    cursor = cy
    for owner, responsibility in ownership:
        s.text(x + 18, cursor, owner, 14, ORANGE, 800)
        s.wrapped(x + 278, cursor, responsibility, w - 296, 13, NAVY)
        cursor += 42
    s.wrapped(x + 18, cy + 244, "Stages remain thin; domain growth belongs in the owning libs/* package.", w - 36, 13, RED, 650)

    y = 1668
    cy = s.panel(x, y, w, 406, "17  CURRENT INVARIANTS & LIMITS", RED, RED_PALE)
    s.bullets(x + 18, cy, [
        "Current hot path is Spark Table / Frame; bounded local pandas is reporting, validation, evaluation, plotting, and final assertions only.",
        "window_features—not historical window_x—is the canonical many-window artifact.",
        "continuous_vector_t_end is the raw ZOH snapshot; event payloads do not overwrite it.",
        "Learned relations support behavioral structure and localization; they do not prove causality.",
        "Current calibration is phase-conditioned empirical tail rarity, narrower than a full conformal framework.",
        "The system emits evidence and explorer artifacts; automated fleet enforcement is not part of the current repository contract.",
    ], w - 36, 14)
    s.rect(x + 18, cy + 303, w - 36, 47, RED, RED, 0, 9)
    s.text(x + w / 2, cy + 334, "CURRENT ≠ GPU-FLEET ROADMAP • THIS PANE DESCRIBES IMPLEMENTED V2", 14, WHITE, 800, "middle")


def build() -> None:
    s = Svg()
    add_header(s)
    add_pipeline(s)
    width = 924
    col1(s, 42, width)
    col2(s, 986, width)
    col3(s, 1930, width)
    col4(s, 2874, width)
    s.line(42, 2092, 3798, 2092, LINE, 1)
    s.text(42, 2120, "Source contracts: README.md • docs/current/v2_architecture.md • fitting_workflow.md • theory_foundations.md • package READMEs • schemas • generated architecture snapshot", 13, MUTED)
    s.text(3798, 2120, "3840 × 2160 • vector-only • regenerate: python tools/render_current_architecture_svg.py", 13, MUTED, 500, "end")
    s.text(42, 2144, "Document class: docs/current active cross-package contract visualization • generated architecture artifacts were inspected, not manually edited", 12, MUTED)
    s.finish()
    print(OUT)


if __name__ == "__main__":
    build()
